# Generated by Django 4.0.2 on 2022-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0005_rename_qualification_user_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_receptionist',
            field=models.BooleanField(default=False),
        ),
    ]
