# Generated by Django 4.0.2 on 2022-05-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0007_drinkselection_branch_menu_branch_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='meal',
            new_name='meals',
        ),
        migrations.AlterField(
            model_name='menu',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restau.branch'),
        ),
    ]
