# Generated by Django 4.0.2 on 2022-05-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0008_rename_meal_order_meals_alter_menu_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkselection',
            name='branch',
        ),
        migrations.AddField(
            model_name='drinkselection',
            name='branch',
            field=models.ManyToManyField(to='restau.Branch'),
        ),
    ]
