# Generated by Django 4.0.2 on 2022-05-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0009_remove_drinkselection_branch_drinkselection_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.order'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='restau.Drink'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.order'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restau.meal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'Recieved'), (2, 'Preparing'), (3, 'Complete'), (4, 'Cancelled'), (5, 'In Transit')], default=0),
        ),
    ]
