# Generated by Django 4.0.2 on 2022-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0002_order_created_by_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_chef',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_waiter',
            field=models.BooleanField(default=False),
        ),
    ]
