# Generated by Django 4.0.2 on 2022-03-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0003_user_is_chef_user_is_customer_user_is_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_status',
            new_name='user_status',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='Qualification',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='uploads/customer/'),
        ),
    ]
