# Generated by Django 4.0.2 on 2022-04-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0006_user_is_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkselection',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restau.branch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restau.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, null=True),
        ),
    ]
